import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Piano from './Piano'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased bg-black font-mono text-white p-4`}>
        <Piano />
        {children}
      </body>
    </html>
  )
}
